-- FSQ Command v8.1 Azure SQL schema
-- The application can also create and upgrade these tables automatically.

IF OBJECT_ID('dbo.Users','U') IS NULL
CREATE TABLE dbo.Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(100) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  Role NVARCHAR(50) NOT NULL,
  Active BIT NOT NULL DEFAULT 1,
  PermissionsJson NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  FolderAccessJson NVARCHAR(MAX) NOT NULL DEFAULT '{}',
  LastLoginAt DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('dbo.AppState','U') IS NULL
CREATE TABLE dbo.AppState (
  StateKey NVARCHAR(150) PRIMARY KEY,
  StateJson NVARCHAR(MAX) NOT NULL,
  UpdatedBy NVARCHAR(100) NULL,
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('dbo.AuditLog','U') IS NULL
CREATE TABLE dbo.AuditLog (
  Id BIGINT IDENTITY(1,1) PRIMARY KEY,
  UserName NVARCHAR(100) NULL,
  Action NVARCHAR(100) NOT NULL,
  EntityType NVARCHAR(100) NULL,
  EntityId NVARCHAR(150) NULL,
  DetailsJson NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('dbo.Projects','U') IS NULL
CREATE TABLE dbo.Projects (
  Id NVARCHAR(100) PRIMARY KEY, ProjectNo NVARCHAR(100), Name NVARCHAR(200) NOT NULL,
  Customer NVARCHAR(200), Type NVARCHAR(50), Status NVARCHAR(50), DataJson NVARCHAR(MAX) NOT NULL,
  UpdatedBy NVARCHAR(100), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('dbo.PlannerEvents','U') IS NULL
CREATE TABLE dbo.PlannerEvents (
  Id NVARCHAR(100) PRIMARY KEY, PersonName NVARCHAR(100), EventType NVARCHAR(50),
  StartDate DATE, EndDate DATE, DataJson NVARCHAR(MAX) NOT NULL,
  UpdatedBy NVARCHAR(100), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('dbo.Machines','U') IS NULL
CREATE TABLE dbo.Machines (
  Id NVARCHAR(100) PRIMARY KEY, Name NVARCHAR(200) NOT NULL, Manufacturer NVARCHAR(200),
  Model NVARCHAR(200), SerialNumber NVARCHAR(200), Location NVARCHAR(200), DataJson NVARCHAR(MAX) NOT NULL,
  UpdatedBy NVARCHAR(100), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('dbo.KnowledgeDocuments','U') IS NULL
CREATE TABLE dbo.KnowledgeDocuments (
  Id NVARCHAR(100) PRIMARY KEY, Name NVARCHAR(260) NOT NULL, FolderName NVARCHAR(200),
  MachineId NVARCHAR(100), BlobName NVARCHAR(1000), DataJson NVARCHAR(MAX) NOT NULL,
  UpdatedBy NVARCHAR(100), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);


IF OBJECT_ID('dbo.ProjectDocuments','U') IS NULL
CREATE TABLE dbo.ProjectDocuments (
  Id NVARCHAR(100) PRIMARY KEY,
  ProjectName NVARCHAR(200) NOT NULL,
  Category NVARCHAR(200) NOT NULL,
  Name NVARCHAR(260) NOT NULL,
  Version INT NOT NULL DEFAULT 1,
  BlobName NVARCHAR(1000) NOT NULL,
  MimeType NVARCHAR(200) NULL,
  SizeBytes BIGINT NULL,
  UploadedBy NVARCHAR(100) NULL,
  IndexStatus NVARCHAR(50) NOT NULL DEFAULT 'Stored',
  IndexError NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
IF OBJECT_ID('dbo.ProjectDocumentChunks','U') IS NULL
CREATE TABLE dbo.ProjectDocumentChunks (
  Id BIGINT IDENTITY(1,1) PRIMARY KEY,
  DocumentId NVARCHAR(100) NOT NULL,
  ChunkNo INT NOT NULL,
  Content NVARCHAR(MAX) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_ProjectDocumentChunks_Document FOREIGN KEY (DocumentId) REFERENCES dbo.ProjectDocuments(Id) ON DELETE CASCADE
);
GO
