import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import JSZip from 'jszip';
import { extractDocumentText } from '../lib/documentText.js';
import { detectImageMime, downloadHeaders, isAllowedDocument, safeSegment } from '../lib/files.js';
import { replaceDocxTemplate, replaceXlsxTemplate, templateFields } from '../lib/templateFill.js';
import { assignmentLabel, clearEmployeeProjectAssignments, isTaskAssignedTo, removeProjectTasks, taskAssignees, taskHasActiveProject } from '../lib/taskAssignments.js';
import { projectPlannerEntries, removeProjectPlannerEntries, syncProjectCrewEntries } from '../lib/plannerSync.js';
import { parseAtlasActionOutput, rankKnowledge } from '../lib/atlas.js';
import fs from 'node:fs';

const workbook = new ExcelJS.Workbook();
const sheet = workbook.addWorksheet('Secure test');
sheet.addRow(['Project', 'Status']);
sheet.addRow(['Wind Orca', 'Ready']);
const xlsxBuffer = Buffer.from(await workbook.xlsx.writeBuffer());
const extracted = await extractDocumentText(
  xlsxBuffer,
  'test.xlsx',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
);
assert.match(extracted, /Wind Orca/);
assert.match(extracted, /Ready/);

assert.deepEqual(templateFields('Kunde {{customer}} PO {{PO_NUMBER}} {{customer}}'), ['CUSTOMER','PO_NUMBER']);
const docxZip = new JSZip();
docxZip.file('word/document.xml', '<w:document><w:r><w:t>{{CUS</w:t></w:r><w:r><w:t>TOMER}}</w:t></w:r><w:t>{{NOTE}}</w:t></w:document>');
docxZip.file('word/footer1.xml', '<w:ftr><w:t>{{PO_NUMBER}}</w:t></w:ftr>');
const docxTemplateBuffer = await docxZip.generateAsync({ type:'nodebuffer' });
const filledDocx = await replaceDocxTemplate(docxTemplateBuffer, {
  CUSTOMER:'FSQ & Partner', NOTE:'Linje 1\nLinje 2', PO_NUMBER:'PO-42'
});
const filledDocxZip = await JSZip.loadAsync(filledDocx);
assert.match(await filledDocxZip.file('word/document.xml').async('string'), /FSQ &amp; Partner/);
assert.match(await filledDocxZip.file('word/document.xml').async('string'), /Linje 1<w:br\/>Linje 2/);
assert.match(await filledDocxZip.file('word/footer1.xml').async('string'), /PO-42/);

const xlsxTemplate = new ExcelJS.Workbook();
const xlsxTemplateSheet = xlsxTemplate.addWorksheet('Template');
xlsxTemplateSheet.getCell('A1').value = 'Customer: {{CUSTOMER}}';
const filledXlsx = await replaceXlsxTemplate(Buffer.from(await xlsxTemplate.xlsx.writeBuffer()), { CUSTOMER:'FSQ' });
const checkedXlsx = new ExcelJS.Workbook();
await checkedXlsx.xlsx.load(filledXlsx);
assert.equal(checkedXlsx.getWorksheet('Template').getCell('A1').value, 'Customer: FSQ');

assert.equal(isAllowedDocument('manual.pdf'), true);
assert.equal(isAllowedDocument('drawing.dwg'), true);
assert.equal(isAllowedDocument('site-photo.jpg'), true);
assert.equal(isAllowedDocument('payload.html'), false);
assert.equal(safeSegment('../../secret'), '..-..-secret');
assert.equal(detectImageMime(Buffer.from([0xff,0xd8,0xff,0x00,0,0,0,0,0,0,0,0])), 'image/jpeg');
assert.equal(detectImageMime(Buffer.from('<svg></svg>')), null);

const riskyHeaders = downloadHeaders({ contentType: 'text/html', filename: 'test.html', inline: true });
assert.match(riskyHeaders.get('Content-Disposition'), /^attachment/);
assert.equal(riskyHeaders.get('X-Content-Type-Options'), 'nosniff');

const sharedTask = { person: 'Tommy', assignees: ['Tommy', 'Jakob', 'Tommy'] };
assert.deepEqual(taskAssignees(sharedTask), ['Tommy', 'Jakob']);
assert.equal(isTaskAssignedTo(sharedTask, 'jakob'), true);
assert.equal(isTaskAssignedTo(sharedTask, 'Flemming'), false);
assert.equal(assignmentLabel(sharedTask), 'Tommy, Jakob');
assert.equal(isTaskAssignedTo({ person: 'Tommy' }, 'Tommy'), true);
assert.equal(taskHasActiveProject({ project: 'Wind Test' }, [{ name: 'Wind Test' }]), true);
assert.equal(taskHasActiveProject({ project: 'Wind Test' }, []), false);
assert.equal(taskHasActiveProject({ project: 'General' }, []), true);
assert.deepEqual(removeProjectTasks([{id:1,project:'Wind Test'},{id:2,project:'General'}], 'wind test').map(task=>task.id), [2]);
assert.deepEqual(clearEmployeeProjectAssignments([{name:'Tommy',project:'Wind Test',task:'Svejsning',progress:50}], 'Wind Test')[0], {name:'Tommy',project:'',task:'No task assigned',progress:0});

const plannedProject = { id: 42, name: 'Wind Test', type: 'Vessel', startDate: '2026-07-20', deadline: '2026-07-22' };
const automaticPlan = projectPlannerEntries(plannedProject, ['Tommy', 'Jakob']);
assert.equal(automaticPlan.length, 6);
assert.equal(automaticPlan[0].source, 'project');
assert.equal(automaticPlan[0].type, 'Marine');
const manualEntry = { key: 'Tommy|2026-07-21', person: 'Tommy', date: '2026-07-21', text: 'Kursus', type: 'Course' };
const syncedPlan = syncProjectCrewEntries([manualEntry], plannedProject, ['Tommy']);
assert.equal(syncedPlan.filter(entry => entry.source === 'project').length, 2);
assert.equal(syncedPlan.find(entry => entry.key === manualEntry.key)?.text, 'Kursus');
assert.equal(removeProjectPlannerEntries([...automaticPlan,manualEntry], plannedProject.id).length, 1);

const atlasOutput = parseAtlasActionOutput('Jeg klarer det.\nATLAS_ACTIONS_JSON: {"actions":[{"type":"create_task","project":"Wind Test","title":"Kontrollér svejsning","people":["Tommy","Jakob"]}]}');
assert.equal(atlasOutput.answer, 'Jeg klarer det.');
assert.equal(atlasOutput.actions[0].type, 'create_task');
assert.deepEqual(atlasOutput.actions[0].people, ['Tommy','Jakob']);
assert.equal(parseAtlasActionOutput('Svar uden handling').actions.length, 0);
const rankedKnowledge = rankKnowledge([{Title:'Andet',Content:'Generelt'},{Title:'Svejsning',Content:'WPS kontrol'}], 'Hjælp med WPS svejsning', 1);
assert.equal(rankedKnowledge[0].Title, 'Svejsning');

const manifest = JSON.parse(fs.readFileSync('public/manifest.webmanifest', 'utf8'));
assert.equal(manifest.display, 'standalone');
assert.ok(manifest.icons.some(icon => icon.purpose === 'maskable'));
const serviceWorker = fs.readFileSync('public/sw.js', 'utf8');
assert.match(serviceWorker, /pathname\.startsWith\('\/api\/'\)/);

const pageSource = fs.readFileSync('app/page.js', 'utf8');
const myJobsSource = pageSource.slice(pageSource.indexOf('function MyJobs('), pageSource.indexOf('function Dashboard('));
const approvalsSource = pageSource.slice(pageSource.indexOf('function JobApprovals('), pageSource.indexOf('function Dashboard('));
const knowledgeSource = pageSource.slice(pageSource.indexOf('function KnowledgeBase('), pageSource.indexOf('function AI('));
assert.doesNotMatch(myJobsSource, /machineDragActive|machineDragDepth/);
assert.match(knowledgeSource, /const \[machineDragActive,setMachineDragActive\]=useState\(false\)/);
assert.match(knowledgeSource, /onDrop=\{machineDrop\}/);
assert.match(pageSource, /\['knowledge', 'Machine Binder', '▤'\]/);
assert.match(pageSource, /\['companyLibrary', 'Company Library', '▧'\]/);
assert.match(pageSource, /function canViewCompanyLibrary\(/);
assert.match(pageSource, /item\[0\] !== 'companyLibrary' \|\| canViewCompanyLibrary\(session\)/);
assert.doesNotMatch(pageSource, /\['myjobs','companyLibrary','inventory'/);
assert.match(pageSource, /function CompanyLibrary\(/);
assert.match(pageSource, /Generér rapportudkast med ATLAS/);
assert.match(pageSource, /Rapporten skal godkendes før print eller download/);
assert.match(pageSource, /FSQ_REPORT_TEMPLATES/);
assert.match(pageSource, /PO → FSQ Packing List/);
assert.match(pageSource, /fsq-v81-company-profile/);
assert.match(pageSource, /companyProfileEditor/);
assert.match(pageSource, /packingEditorTable/);
assert.match(pageSource, /Generér FSQ-pakkeliste automatisk/);
assert.match(pageSource, /CVR\/VAT/);
assert.match(pageSource, /fsq-logo-clean\.webp/);
assert.match(pageSource, /Udfyld FSQ-template/);
assert.match(pageSource, /templateStudioGrid/);
assert.match(pageSource, /\{\{CUSTOMER\}\}/);
assert.match(pageSource, /Lad ATLAS udfylde template/);
assert.match(pageSource, /downloadFilledTemplate/);
assert.match(pageSource, /WPS_FIELD_GROUPS/);
assert.match(pageSource, /\/api\/atlas\/wps/);
assert.match(pageSource, /Generér WPS/);
assert.match(pageSource, /FSQ-logo er låst i Word-masteren/);
assert.match(pageSource, /WPS kan ikke godkendes endnu/);
assert.match(pageSource, /Download FSQ WPS · Word/);
assert.match(pageSource, /WPS_SIMPLE_FIELDS/);
assert.match(pageSource, /Enkel WPS-visning/);
assert.match(pageSource, /Vis avancerede felter/);
assert.match(pageSource, /WPS_MATERIAL_OPTIONS/);
assert.match(pageSource, /WPS_PROCESS_OPTIONS/);
assert.match(pageSource, /Stumpsøm/);
assert.match(pageSource, /Kantsøm/);
assert.match(pageSource, /GENERÉR FSQ WPS/);
assert.match(pageSource, /Create a simple English FSQ Welding Procedure Specification/);
assert.match(pageSource, /className="atlasCommandDeck"/);
assert.match(pageSource, /className="atlasMegaCore"/);
assert.match(pageSource, /className="atlasCommandInput"/);
assert.match(pageSource, /if \(!projectsHydrated \|\| !tasksHydrated\) return/);
assert.match(pageSource, /setTasks\(cleanedTasks\)/);
assert.match(pageSource, /normalizeStoredValue\(data\.value, initialValue\)/);
assert.match(pageSource, /Workshop control active <span\/> v\{APP_VERSION\}/);
assert.match(pageSource, /\['131','MIG solid wire'\]/);
assert.match(pageSource, /SMO 254 \/ 1\.4547 \(6Mo\)/);
assert.match(pageSource, /Use exact filler wire from selected WPQR/);
assert.match(pageSource, /WPS_POSITION_OPTIONS/);
assert.match(pageSource, /Flat position \(liggende\)/);
assert.match(pageSource, /migrateLegacyWorkshopControl/);
assert.match(pageSource, /Medarbejderen fjernes fra login, Crew, projekter, jobs og oversigtsplanen/);
assert.match(pageSource, /setPlannerEntries\(current=>current\.filter\(entry=>!matches\(entry\.person\)\)\)/);
assert.match(pageSource, /setPeople\(current=>current\.filter\(person=>!matches\(person\.name\)\)\)/);
assert.match(pageSource, /if\(!userDeleted\)/);
assert.match(pageSource, /function JobArchive\(/);
assert.match(pageSource, /archiveReason:'Final control approved'/);
assert.match(pageSource, /function canApproveWorkshopFinal/);
assert.match(pageSource, /item\[0\] !== 'approvals' \|\| canApproveWorkshopFinal\(session\)/);
assert.match(myJobsSource, /Jobbet er færdigt – tag 4 afslutningsbilleder/);
assert.match(myJobsSource, /Afslut job og send til slutkontrol/);
assert.match(myJobsSource, /Math\.max\(0,4-\(selected\.photos\|\|\[\]\)\.length\)/);
assert.doesNotMatch(myJobsSource, /function submitTack/);
assert.doesNotMatch(myJobsSource, /function startWelding/);
assert.match(approvalsSource, /Kun Flemming og Jakob har adgang/);
assert.match(approvalsSource, /Godkend slutkontrol og afslut job/);
assert.doesNotMatch(approvalsSource, /approveTack|tackPending/);
assert.match(pageSource, /active === 'jobArchive'/);
assert.match(pageSource, /\['fleet', 'Fleet Map', '⌖'\]/);
assert.match(pageSource, /function FleetMap\(/);
assert.match(pageSource, /MMSI · live tracking/);
assert.match(pageSource, /function isMarineProject\(/);
assert.match(pageSource, /Open tracking settings/);
assert.match(pageSource, /Vessel tracking/);
assert.match(pageSource, /OpenAI key missing/);
assert.match(pageSource, /30 SEC REFRESH/);
assert.match(pageSource, /WAITING FOR SIGNAL/);
assert.match(pageSource, /exactly 9 digits/i);
assert.match(pageSource, /NIBE · FSQ HQ/);
assert.match(pageSource, /const FLEET_MAP_CITIES/);
assert.match(pageSource, /className="shippingRoutes"/);
assert.match(pageSource, /world-map-natural-earth\.svg/);
assert.match(pageSource, /className="continentLabels"/);
assert.match(pageSource, /setActive\(id\);setMobileNavOpen\(false\)/);
assert.doesNotMatch(pageSource, /src="\/fsq-logo\.jpg"/);
assert.ok(fs.statSync('public/fsq-logo-clean.webp').size > 1000);
const stylesSource = fs.readFileSync('app/styles.css', 'utf8');
assert.match(stylesSource, /min-height:56px/);
assert.match(stylesSource, /inset:calc\(env\(safe-area-inset-top\) \+ 12px\)/);
assert.match(stylesSource, /border-radius:0 18px 18px 0/);
assert.match(stylesSource, /min-height:calc\(72px \+ env\(safe-area-inset-top\)\)/);
assert.match(stylesSource, /max-height:680px/);
assert.match(stylesSource, /\.atlasMegaCore\{/);
assert.match(stylesSource, /@media\(max-width:650px\)\{\.atlasCommandDeck/);
assert.match(stylesSource, /@media\(max-width:1650px\)\{\.machineBinderLayout\{grid-template-columns:/);
assert.match(stylesSource, /\.machineBinderDocuments,\.machineBinderPreview\{grid-column:1\/-1;min-height:auto\}/);
assert.match(stylesSource, /\.machineFolderCreate input\{width:100%;min-width:0\}/);
assert.match(stylesSource, /\.reportStudioGrid\{/);
assert.match(stylesSource, /\.reportApprovalBar\{/);
assert.match(stylesSource, /\.fleetLayout\{/);
assert.match(stylesSource, /\.worldMap\{/);
assert.match(stylesSource, /\.projectTrackingPanel\{/);
assert.match(stylesSource, /\.atlasConfigWarning\{/);
assert.match(stylesSource, /\.mapCity\.home\{/);
assert.match(stylesSource, /@keyframes mapRouteFlow/);
assert.match(stylesSource, /\.naturalEarthMap\{/);
const worldMapSvg = fs.readFileSync('public/world-map-natural-earth.svg','utf8');
assert.match(worldMapSvg, /Natural Earth world map/);
assert.ok((worldMapSvg.match(/class="country/g)||[]).length > 170);

const reportRoute = fs.readFileSync('app/api/atlas/report/route.js', 'utf8');
assert.match(reportRoute, /Use only facts visible/);
assert.match(reportRoute, /MAX_TOTAL_SIZE/);
assert.match(reportRoute, /store: false/);
assert.match(reportRoute, /packingDetails/);
assert.match(reportRoute, /packingItems/);
assert.match(reportRoute, /Extract every PO line/);
assert.match(reportRoute, /Do not guess package numbers/);
const templateRoute = fs.readFileSync('app/api/atlas/template/route.js', 'utf8');
assert.match(templateRoute, /canAccessCompanyLibrary/);
assert.match(templateRoute, /replaceDocxTemplate/);
assert.match(templateRoute, /replaceXlsxTemplate/);
assert.match(templateRoute, /Never invent names, dates, measurements/);
assert.match(templateRoute, /MANGLER/);
assert.match(templateRoute, /Cache-Control':'private, no-store/);
const wpsRoute = fs.readFileSync('app/api/atlas/wps/route.js', 'utf8');
assert.match(wpsRoute, /Controlled WPS\/WPQR source/);
assert.match(wpsRoute, /type: 'input_file'/);
assert.match(wpsRoute, /replaceDocxTemplate/);
assert.match(wpsRoute, /confirmTechnicalReview/);
assert.match(wpsRoute, /canAccessCompanyLibrary/);
assert.match(wpsRoute, /FSQ-WPS-Master\.docx/);
assert.match(wpsRoute, /Never calculate, infer or expand qualification ranges/);
assert.match(wpsRoute, /RUN_1_CURRENT/);
assert.match(wpsRoute, /Optional fields without controlled source data/);
const wpsMasterBuffer = fs.readFileSync('public/templates/FSQ-WPS-Master.docx');
assert.ok(wpsMasterBuffer.length > 100000);
const wpsMaster = await JSZip.loadAsync(wpsMasterBuffer);
assert.ok(Object.keys(wpsMaster.files).some(name => /^word\/media\/image/i.test(name)));
const wpsMasterXml = await wpsMaster.file('word/document.xml').async('string');
assert.match(wpsMasterXml, /\{\{WPS_NO\}\}/);
assert.match(wpsMasterXml, /\{\{SUPPORTING_WPQR\}\}/);
assert.match(wpsMasterXml, /WELDING PROCEDURE SPECIFICATION/);
assert.match(wpsMasterXml, /BUTT WELD/);
assert.match(wpsMasterXml, /FILLET WELD/);
assert.match(wpsMasterXml, /\{\{RUN_1_CURRENT\}\}/);
const stateRoute = fs.readFileSync('app/api/state/route.js', 'utf8');
assert.match(stateRoute, /fsq-v81-company-profile/);
assert.match(stateRoute, /PRIVATE_COMPANY_KEYS/);
const databaseSource = fs.readFileSync('lib/db.js', 'utf8');
assert.match(databaseSource, /TOKEN_RENEWAL_WINDOW_MS/);
assert.match(databaseSource, /poolTokenExpiresOnTimestamp/);
assert.match(databaseSource, /ManagedIdentityCredential/);
const loginUsersRoute = fs.readFileSync('app/api/auth/users/route.js', 'utf8');
assert.match(loginUsersRoute, /MANAGED_IDENTITY_SQL_LOGIN/);
assert.match(loginUsersRoute, /await resetPool\(\)/);
assert.equal(JSON.parse(fs.readFileSync('package.json','utf8')).dependencies.jszip, '3.10.1');
const fleetRoute = fs.readFileSync('app/api/fleet/positions/route.js', 'utf8');
assert.match(fleetRoute, /AISSTREAM_API_KEY/);
assert.match(fleetRoute, /readSession/);
assert.match(fleetRoute, /function ensureLiveStream/);
assert.match(fleetRoute, /waitForFirstPosition/);
assert.match(fleetRoute, /connectionStatus/);
assert.match(fleetRoute, /function scheduleReconnect/);
assert.match(fleetRoute, /function stopLiveStream/);
assert.match(fleetRoute, /AISstream rejected AISSTREAM_API_KEY/);
assert.match(fleetRoute, /nextReconnectAt/);
assert.match(pageSource, /reconnecting:'◌ RECONNECTING'/);
assert.doesNotMatch(fleetRoute, /setTimeout\(finish, 5_500\)/);
assert.doesNotMatch(pageSource, /AISSTREAM_API_KEY/);
assert.match(fs.readFileSync('app/api/atlas/chat/route.js','utf8'), /OPENAI_API_KEY mangler/);

console.log('Smoke tests passed (documents, reports, downloads, crew assignment, Machine Binder and mobile app).');
